<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class KategoriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('kategoriler')->insert([
            '0' => [
                'kategori_adi' => 'Tarım Alet ve Makineleri',
                'slug' => Str::slug('Tarım Alet ve Makineleri'),
                'ust_kategori' => null,
                'sira' => 1,
            ],
            '1' => [
                'kategori_adi' => 'Traktör',
                'slug' => Str::slug('Traktör'),
                'ust_kategori' => 1,
                'sira' => 1,
            ],
            '2' => [
                'kategori_adi' => 'New Holland',
                'slug' => Str::slug('New Holland'),
                'ust_kategori' => 2,
                'sira' => 1,
            ],
            '3' => [
                'kategori_adi' => 'Massey Ferguson',
                'slug' => Str::slug('Massey Ferguson'),
                'ust_kategori' => 2,
                'sira' => 2,
            ],
            '4' => [
                'kategori_adi' => 'Case IH',
                'slug' => Str::slug('Case IH'),
                'ust_kategori' => 2,
                'sira' => 3,
            ],
            '5' => [
                'kategori_adi' => 'Fiat',
                'slug' => Str::slug('Fiat'),
                'ust_kategori' => 2,
                'sira' => 4,
            ],
            '6' => [
                'kategori_adi' => 'John Deere',
                'slug' => Str::slug('John Deere'),
                'ust_kategori' => 2,
                'sira' => 5,
            ],
            '7' => [
                'kategori_adi' => 'Erkunt',
                'slug' => Str::slug('Erkunt'),
                'ust_kategori' => 2,
                'sira' => 6,
            ],
            '8' => [
                'kategori_adi' => 'Hattat',
                'slug' => Str::slug('Hattat'),
                'ust_kategori' => 2,
                'sira' => 7,
            ],
            '9' => [
                'kategori_adi' => 'Toprak İşleme',
                'slug' => Str::slug('Toprak İşleme'),
                'ust_kategori' => 1,
                'sira' => 2,
            ],
            '10' => [
                'kategori_adi' => 'Ağaç Sökme',
                'slug' => Str::slug('Ağaç Sökme'),
                'ust_kategori' => 10,
                'sira' => 1,
            ],
            '11' => [
                'kategori_adi' => 'Çapalama',
                'slug' => Str::slug('Çapalama'),
                'ust_kategori' => 10,
                'sira' => 2,
            ],
            '12' => [
                'kategori_adi' => 'Çizer Dipkazan',
                'slug' => Str::slug('Çizer Dipkazan'),
                'ust_kategori' => 10,
                'sira' => 3,
            ],
            '13' => [
                'kategori_adi' => 'Diskaro',
                'slug' => Str::slug('Diskaro'),
                'ust_kategori' => 10,
                'sira' => 4,
            ],
            '14' => [
                'kategori_adi' => 'Kültivatör',
                'slug' => Str::slug('Kültivatör'),
                'ust_kategori' => 10,
                'sira' => 5,
            ],
            '15' => [
                'kategori_adi' => 'Lazer Tesviye & Düzleme',
                'slug' => Str::slug('Lazer Tesviye & Düzleme'),
                'ust_kategori' => 10,
                'sira' => 6,
            ],
            '16' => [
                'kategori_adi' => 'Malç Makinesı',
                'slug' => Str::slug('Malç Makinesı'),
                'ust_kategori' => 10,
                'sira' => 7,
            ],
            '17' => [
                'kategori_adi' => 'Odun Kırma',
                'slug' => Str::slug('Odun Kırma'),
                'ust_kategori' => 10,
                'sira' => 8,
            ],
            '18' => [
                'kategori_adi' => 'Pulluk',
                'slug' => Str::slug('Pulluk'),
                'ust_kategori' => 10,
                'sira' => 9,
            ],
            '19' => [
                'kategori_adi' => 'Rotovatör',
                'slug' => Str::slug('Rotovatör'),
                'ust_kategori' => 10,
                'sira' => 10,
            ],
            '20' => [
                'kategori_adi' => 'Sap Parçalama',
                'slug' => Str::slug('Sap Parçalama'),
                'ust_kategori' => 10,
                'sira' => 11,
            ],
            '21' => [
                'kategori_adi' => 'Sırt Yapma',
                'slug' => Str::slug('Sırt Yapma'),
                'ust_kategori' => 10,
                'sira' => 12,
            ],
            '22' => [
                'kategori_adi' => 'Taş Kırma',
                'slug' => Str::slug('Taş Kırma'),
                'ust_kategori' => 10,
                'sira' => 13,
            ],
            '23' => [
                'kategori_adi' => 'Tırmık',
                'slug' => Str::slug('Tırmık'),
                'ust_kategori' => 10,
                'sira' => 14,
            ],
            '24' => [
                'kategori_adi' => 'Toprak Çim Havalandırma',
                'slug' => Str::slug('Toprak Çim Havalandırma'),
                'ust_kategori' => 10,
                'sira' => 15,
            ],
            '25' => [
                'kategori_adi' => 'Toprak Burgu Makinesi',
                'slug' => Str::slug('Toprak Burgu Makinesi'),
                'ust_kategori' => 10,
                'sira' => 16,
            ],
            '26' => [
                'kategori_adi' => 'Toprak Öğütme Makinesi',
                'slug' => Str::slug('Toprak Öğütme Makinesi'),
                'ust_kategori' => 10,
                'sira' => 17,
            ],
            '27' => [
                'kategori_adi' => 'Hasat & Harman',
                'slug' => Str::slug('Hasat & Harman'),
                'ust_kategori' => 1,
                'sira' => 3,
            ],
            '28' => [
                'kategori_adi' => 'Biçerdöver',
                'slug' => Str::slug('Biçerdöver'),
                'ust_kategori' => 28,
                'sira' => 1,
            ],
            '29' => [
                'kategori_adi' => 'Ağaç Silkeleme Makinesi',
                'slug' => Str::slug('Ağaç Silkeleme Makinesi'),
                'ust_kategori' => 28,
                'sira' => 2,
            ],
            '30' => [
                'kategori_adi' => 'Ayçiçeği Patoz & Toplama',
                'slug' => Str::slug('Ayçiçeği Patoz & Toplama'),
                'ust_kategori' => 28,
                'sira' => 3,
            ],
            '31' => [
                'kategori_adi' => 'Balya Makinesi',
                'slug' => Str::slug('Balya Makinesi'),
                'ust_kategori' => 28,
                'sira' => 4,
            ],
            '32' => [
                'kategori_adi' => 'Biçerbağlar',
                'slug' => Str::slug('Biçerbağlar'),
                'ust_kategori' => 28,
                'sira' => 5,
            ],
            '33' => [
                'kategori_adi' => 'Boylama Makinesi',
                'slug' => Str::slug('Boylama Makinesi'),
                'ust_kategori' => 28,
                'sira' => 6,
            ],
            '34' => [
                'kategori_adi' => 'Çırçır Makinesi',
                'slug' => Str::slug('Çırçır Makinesi'),
                'ust_kategori' => 28,
                'sira' => 7,
            ],
            '35' => [
                'kategori_adi' => 'Domates Toplama Makinesi',
                'slug' => Str::slug('Domates Toplama Makinesi'),
                'ust_kategori' => 28,
                'sira' => 8,
            ],
            '36' => [
                'kategori_adi' => 'Fındık Patoz & Toplama',
                'slug' => Str::slug('Fındık Patoz & Toplama'),
                'ust_kategori' => 28,
                'sira' => 9,
            ],
            '37' => [
                'kategori_adi' => 'Fıstık Hasat Makinesi',
                'slug' => Str::slug('Fındık Hasat Makinesi'),
                'ust_kategori' => 28,
                'sira' => 10,
            ],
            '38' => [
                'kategori_adi' => 'Harman Makinesi',
                'slug' => Str::slug('Harman Makinesi'),
                'ust_kategori' => 28,
                'sira' => 11,
            ],
            '39' => [
                'kategori_adi' => 'Kurutma Makinesi',
                'slug' => Str::slug('Kurutma Makinesi'),
                'ust_kategori' => 28,
                'sira' => 12,
            ],
            '40' => [
                'kategori_adi' => 'Meyve Zeytin Toplama',
                'slug' => Str::slug('Meyve Zeytin Toplama'),
                'ust_kategori' => 28,
                'sira' => 13,
            ],
            '41' => [
                'kategori_adi' => 'Mısır Hasat Tablası',
                'slug' => Str::slug('Mısır Hasat Tablası'),
                'ust_kategori' => 28,
                'sira' => 14,
            ],
            '42' => [
                'kategori_adi' => 'Pamuk Toplama Makinesi',
                'slug' => Str::slug('Pamuk Toplama Makinesi'),
                'ust_kategori' => 28,
                'sira' => 15,
            ],
            '43' => [
                'kategori_adi' => 'Pancar Sökme Makinesi',
                'slug' => Str::slug('Pancar Sökme Makinesi'),
                'ust_kategori' => 28,
                'sira' => 16,
            ],
            '44' => [
                'kategori_adi' => 'Patates Soğan Sökme',
                'slug' => Str::slug('Patates Soğan Sökme'),
                'ust_kategori' => 28,
                'sira' => 16,
            ],
            '45' => [
                'kategori_adi' => 'Pirinç Hasat Makinesi',
                'slug' => Str::slug('Pirinç Hasat Makinesi'),
                'ust_kategori' => 28,
                'sira' => 17,
            ],
            '46' => [
                'kategori_adi' => 'Prinç Hasat Makinesi',
                'slug' => Str::slug('Prinç Hasat Makinesi'),
                'ust_kategori' => 28,
                'sira' => 18,
            ],
            '47' => [
                'kategori_adi' => 'Saman Makinesi',
                'slug' => Str::slug('Saman Makinesi'),
                'ust_kategori' => 28,
                'sira' => 19,
            ],
            '48' => [
                'kategori_adi' => 'Silaj Makinesi',
                'slug' => Str::slug('Silaj Makinesi'),
                'ust_kategori' => 28,
                'sira' => 20,
            ],
            '49' => [
                'kategori_adi' => 'Silaj Paketleme Makinesi',
                'slug' => Str::slug('Silaj Paketleme Makinesi'),
                'ust_kategori' => 28,
                'sira' => 21,
            ],
            '50' => [
                'kategori_adi' => 'Soyma Makinesi',
                'slug' => Str::slug('Soyma Makinesi'),
                'ust_kategori' => 28,
                'sira' => 22,
            ],
            '51' => [
                'kategori_adi' => 'Tohum Eleme Makinesi',
                'slug' => Str::slug('Tohum Eleme Makinesi'),
                'ust_kategori' => 28,
                'sira' => 23,
            ],
            '52' => [
                'kategori_adi' => 'Zeytin Eleme Makinesi',
                'slug' => Str::slug('Zeytin Eleme Makinesi'),
                'ust_kategori' => 28,
                'sira' => 24,
            ],
            '53' => [ // Top Category
                'kategori_adi' => 'Bitki Bakım',
                'slug' => Str::slug('Bitki Bakım'),
                'ust_kategori' => 1,
                'sira' => 4,
            ],
            '54' => [
                'kategori_adi' => 'Budama Makinesi',
                'slug' => Str::slug('Budama Makinesi'),
                'ust_kategori' => 54,
                'sira' => 1,
            ],
            '55' => [
                'kategori_adi' => 'Çayır, Çim & Ot Biçme',
                'slug' => Str::slug('Çayır, Çim & Ot Biçme'),
                'ust_kategori' => 54,
                'sira' => 2,
            ],
            '56' => [
                'kategori_adi' => 'Orak & Tırpan Makinesi',
                'slug' => Str::slug('Orak & Tırpan Makinesi'),
                'ust_kategori' => 54,
                'sira' => 3,
            ],
            '57' => [
                'kategori_adi' => 'Palet Makinesi',
                'slug' => Str::slug('Palet Makinesi'),
                'ust_kategori' => 54,
                'sira' => 4,
            ],
            '58' => [
                'kategori_adi' => 'Talaş Hazırlama',
                'slug' => Str::slug('Talaş Hazırlama'),
                'ust_kategori' => 54,
                'sira' => 5,
            ],
            '59' => [
                'kategori_adi' => 'Üfleme Toplama Makinesi',
                'slug' => Str::slug('Üfleme Toplama Makinesi'),
                'ust_kategori' => 54,
                'sira' => 5,
            ],
            '60' => [
                'kategori_adi' => 'Yaprak ve Dal Öğütme Makinesi',
                'slug' => Str::slug('Yaprak ve Dal Öğütme Makinesi'),
                'ust_kategori' => 54,
                'sira' => 6,
            ],
            '61' => [
                'kategori_adi' => 'Ekim & Dikim',
                'slug' => Str::slug('Ekim & Dikim'),
                'ust_kategori' => 1,
                'sira' => 5,
            ],
            '62' => [
                'kategori_adi' => 'Ekim Makinesi',
                'slug' => Str::slug('Ekim Makinesi'),
                'ust_kategori' => 62,
                'sira' => 1,
            ],
            '63' => [
                'kategori_adi' => 'Hubutat Ekim Mibzeri',
                'slug' => Str::slug('Hubutat Ekim Mibzeri'),
                'ust_kategori' => 62,
                'sira' => 2,
            ],
            '64' => [
                'kategori_adi' => 'Patates & Soğan Ekme',
                'slug' => Str::slug('Patates & Soğan Ekme'),
                'ust_kategori' => 62,
                'sira' => 3,
            ],
            '65' => [
                'kategori_adi' => 'Tütün Dikim Makinesi',
                'slug' => Str::slug('Tütün Dikim Makinesi'),
                'ust_kategori' => 62,
                'sira' => 4,
            ],
            '66' => [
                'kategori_adi' => 'Gübreleme',
                'slug' => Str::slug('Gübreleme'),
                'ust_kategori' => 1,
                'sira' => 6,
            ],
            '67' => [
                'kategori_adi' => 'Gübre Dağıtma & Serpme',
                'slug' => Str::slug('Gübre Dağıtma & Serpme'),
                'ust_kategori' => 67,
                'sira' => 1,
            ],
            '68' => [
                'kategori_adi' => 'Gübre Karıştırıcı',
                'slug' => Str::slug('Gübre Karıştırıcı'),
                'ust_kategori' => 67,
                'sira' => 2,
            ],
            '69' => [
                'kategori_adi' => 'Gübre Kurutma Makinesi',
                'slug' => Str::slug('Gübre Kurutma Makinesi'),
                'ust_kategori' => 67,
                'sira' => 3,
            ],
            '70' => [
                'kategori_adi' => 'Gübre Parçalama',
                'slug' => Str::slug('Gübre Parçalama'),
                'ust_kategori' => 67,
                'sira' => 4,
            ],
            '71' => [
                'kategori_adi' => 'Gübre Pompası',
                'slug' => Str::slug('Gübre Pompası'),
                'ust_kategori' => 67,
                'sira' => 5,
            ],
            '72' => [
                'kategori_adi' => 'Gübre Seperatörü',
                'slug' => Str::slug('Gübre Seperatörü'),
                'ust_kategori' => 67,
                'sira' => 6,
            ],
            '73' => [
                'kategori_adi' => 'Gübre Sıyırıcı',
                'slug' => Str::slug('Gübre Sıyırıcı'),
                'ust_kategori' => 67,
                'sira' => 7,
            ],
            '74' => [
                'kategori_adi' => 'Kompost Makinesi',
                'slug' => Str::slug('Kompost Makinesi'),
                'ust_kategori' => 67,
                'sira' => 8,
            ],
            '75' => [
                'kategori_adi' => 'Sulama',
                'slug' => Str::slug('Sulama'),
                'ust_kategori' => 1,
                'sira' => 7,
            ],
            '76' => [
                'kategori_adi' => 'Gübre Tankı',
                'slug' => Str::slug('Gübre Tankı'),
                'ust_kategori' => 76,
                'sira' => 1,
            ],
            '77' => [
                'kategori_adi' => 'Pancar Motoru',
                'slug' => Str::slug('Pancar Motoru'),
                'ust_kategori' => 76,
                'sira' => 2,
            ],
            '78' => [
                'kategori_adi' => 'Sulama Makinesi',
                'slug' => Str::slug('Sulama Makinesi'),
                'ust_kategori' => 76,
                'sira' => 3,
            ],
            '79' => [
                'kategori_adi' => 'Su Pompası & Motoru',
                'slug' => Str::slug('Su Pompası & Motoru'),
                'ust_kategori' => 76,
                'sira' => 4,
            ],
            '80' => [
                'kategori_adi' => 'Su Tankeri',
                'slug' => Str::slug('Su Tankeri'),
                'ust_kategori' => 76,
                'sira' => 5,
            ],
            '81' => [
                'kategori_adi' => 'Taşıma',
                'slug' => Str::slug('Taşıma'),
                'ust_kategori' => 1,
                'sira' => 8,
            ],
            '82' => [
                'kategori_adi' => 'Römork',
                'slug' => Str::slug('Römork'),
                'ust_kategori' => 82,
                'sira' => 1,
            ],
            '83' => [
                'kategori_adi' => 'Konveyör, Bant & Helezon',
                'slug' => Str::slug('Konveyör, Bant & Helezon'),
                'ust_kategori' => 82,
                'sira' => 2,
            ],
            '84' => [
                'kategori_adi' => 'Tomruk Çekici Vinç',
                'slug' => Str::slug('Tomruk Çekici Vinç'),
                'ust_kategori' => 82,
                'sira' => 3,
            ],
            '85' => [
                'kategori_adi' => 'Yedek Parça',
                'slug' => Str::slug('Yedek Parça'),
                'ust_kategori' => 1,
                'sira' => 9,
            ],
            '86' => [
                'kategori_adi' => 'Sıfır Parça',
                'slug' => Str::slug('Sıfır Parça'),
                'ust_kategori' => 86,
                'sira' => 1,
            ],
            '87' => [
                'kategori_adi' => '2. El Parça',
                'slug' => Str::slug('2. El Parça'),
                'ust_kategori' => 86,
                'sira' => 2,
            ],
            '88' => [
                'kategori_adi' => 'Arazi',
                'slug' => Str::slug('Arazi'),
                'ust_kategori' => null,
                'sira' => 2,
            ],
            '89' => [
                'kategori_adi' => 'Satılık',
                'slug' => Str::slug('Satılık'),
                'ust_kategori' => 89,
                'sira' => 1,
            ],
            '90' => [
                'kategori_adi' => 'Arsa',
                'slug' => Str::slug('Arsa'),
                'ust_kategori' => 90,
                'sira' => 1,
            ],
            '91' => [
                'kategori_adi' => 'Bağ & Bahçe',
                'slug' => Str::slug('Bağ & Bahçe'),
                'ust_kategori' => 90,
                'sira' => 2,
            ],
            '92' => [
                'kategori_adi' => 'Tarla',
                'slug' => Str::slug('Tarla'),
                'ust_kategori' => 90,
                'sira' => 3,
            ],
            '93' => [
                'kategori_adi' => 'Depo & Antrepo',
                'slug' => Str::slug('Depo & Antrepo'),
                'ust_kategori' => 90,
                'sira' => 4,
            ],
            '94' => [
                'kategori_adi' => 'Çiftlik',
                'slug' => Str::slug('Çiftlik'),
                'ust_kategori' => 90,
                'sira' => 5,
            ],
            '95' => [
                'kategori_adi' => 'Sera',
                'slug' => Str::slug('Sera'),
                'ust_kategori' => 90,
                'sira' => 6,
            ],
            '96' => [
                'kategori_adi' => 'Diğer',
                'slug' => Str::slug('Diğer'),
                'ust_kategori' => 90,
                'sira' => 7,
            ],
            '97' => [
                'kategori_adi' => 'Kiralık',
                'slug' => Str::slug('Kiralık'),
                'ust_kategori' => 89,
                'sira' => 2,
            ],
            '98' => [
                'kategori_adi' => 'Arsa',
                'slug' => Str::slug('Arsa'),
                'ust_kategori' => 98,
                'sira' => 1,
            ],
            '99' => [
                'kategori_adi' => 'Bağ & Bahçe',
                'slug' => Str::slug('Bağ & Bahçe'),
                'ust_kategori' => 98,
                'sira' => 2,
            ],
            '100' => [
                'kategori_adi' => 'Tarla',
                'slug' => Str::slug('Tarla'),
                'ust_kategori' => 98,
                'sira' => 3,
            ],
            '101' => [
                'kategori_adi' => 'Depo & Antrepo',
                'slug' => Str::slug('Depo & Antrepo'),
                'ust_kategori' => 98,
                'sira' => 4,
            ],
            '102' => [
                'kategori_adi' => 'Çiftlik',
                'slug' => Str::slug('Çiftlik'),
                'ust_kategori' => 98,
                'sira' => 5,
            ],
            '103' => [
                'kategori_adi' => 'Sera',
                'slug' => Str::slug('Sera'),
                'ust_kategori' => 98,
                'sira' => 6,
            ],
            '104' => [
                'kategori_adi' => 'Diğer',
                'slug' => Str::slug('Diğer'),
                'ust_kategori' => 90,
                'sira' => 7,
            ],
            '105' => [
                'kategori_adi' => 'Fidan - Fide',
                'slug' => Str::slug('Fidan - Fide'),
                'ust_kategori' => null,
                'sira' => 3,
            ],
            '106' => [
                'kategori_adi' => 'Sebze Fideleri',
                'slug' => Str::slug('Sebze Fideleri'),
                'ust_kategori' => 106,
                'sira' => 1,
            ],
            '107' => [
                'kategori_adi' => 'Meyve Fideleri',
                'slug' => Str::slug('Meyve Fideleri'),
                'ust_kategori' => 106,
                'sira' => 2,
            ],
            '108' => [
                'kategori_adi' => 'Süs Bitkileri',
                'slug' => Str::slug('Süs Bitkileri'),
                'ust_kategori' => 106,
                'sira' => 3,
            ],
            '109' => [
                'kategori_adi' => 'Pencere Önü Bitkileri',
                'slug' => Str::slug('Pencere Önü Bitkileri'),
                'ust_kategori' => 106,
                'sira' => 4,
            ],
            '110' => [
                'kategori_adi' => 'Diğer',
                'slug' => Str::slug('Diğer'),
                'ust_kategori' => 106,
                'sira' => 5,
            ],
            '111' => [
                'kategori_adi' => 'Gübre - İlaç',
                'slug' => Str::slug('Gübre - İlaç'),
                'ust_kategori' => null,
                'sira' => 4,
            ],
            '112' => [
                'kategori_adi' => 'Bitki Besini & İlaçları',
                'slug' => Str::slug('Bitki Besini & İlaçları'),
                'ust_kategori' => 112,
                'sira' => 1,
            ],
            '113' => [
                'kategori_adi' => 'Bitki Yetiştirme Lambaları',
                'slug' => Str::slug('Bitki Yetiştirme Lambaları'),
                'ust_kategori' => 112,
                'sira' => 2,
            ],
            '114' => [
                'kategori_adi' => 'Elektrik & Aksesuarları',
                'slug' => Str::slug('Elektrik & Aksesuarları'),
                'ust_kategori' => 112,
                'sira' => 3,
            ],
            '115' => [
                'kategori_adi' => 'Gübre',
                'slug' => Str::slug('Gübre'),
                'ust_kategori' => 112,
                'sira' => 4,
            ],
            '116' => [
                'kategori_adi' => 'Toprak',
                'slug' => Str::slug('Toprak'),
                'ust_kategori' => 112,
                'sira' => 5,
            ],
            '117' => [
                'kategori_adi' => 'Diğer',
                'slug' => Str::slug('Diğer'),
                'ust_kategori' => 112,
                'sira' => 6,
            ],
            '118' => [
                'kategori_adi' => 'Tohum',
                'slug' => Str::slug('Tohum'),
                'ust_kategori' => null,
                'sira' => 5,
            ],
            '119' => [
                'kategori_adi' => 'Çiçek Tohumlar',
                'slug' => Str::slug('Çiçek Tohumlar'),
                'ust_kategori' => 119,
                'sira' => 1,
            ],
            '120' => [
                'kategori_adi' => 'Çim Tohumları',
                'slug' => Str::slug('Çim Tohumları'),
                'ust_kategori' => 119,
                'sira' => 2,
            ],
            '121' => [
                'kategori_adi' => 'Meyve Ağacı Tohumları',
                'slug' => Str::slug('Meyve Ağacı Tohumları'),
                'ust_kategori' => 119,
                'sira' => 3,
            ],
            '122' => [
                'kategori_adi' => 'Sebze Tohumları',
                'slug' => Str::slug('Sebze Tohumları'),
                'ust_kategori' => 119,
                'sira' => 4,
            ],
            '123' => [
                'kategori_adi' => 'Tibbi Aromatik Tohumları',
                'slug' => Str::slug('Tibbi Aromatik Tohumları'),
                'ust_kategori' => 119,
                'sira' => 5,
            ],
            '124' => [
                'kategori_adi' => 'Süs Bitkisi Tohumları',
                'slug' => Str::slug('Süs Bitkisi Tohumları'),
                'ust_kategori' => 119,
                'sira' => 6,
            ],
            '125' => [
                'kategori_adi' => 'Orman Ağacı Tohumları',
                'slug' => Str::slug('Orman Ağacı Tohumları'),
                'ust_kategori' => 119,
                'sira' => 7,
            ],
            '126' => [
                'kategori_adi' => 'Diğer',
                'slug' => Str::slug('Diğer'),
                'ust_kategori' => 119,
                'sira' => 8,
            ],
            '127' => [
                'kategori_adi' => 'Tarım İşçileri',
                'slug' => Str::slug('Tarım İşçileri'),
                'ust_kategori' => null,
                'sira' => 6,
            ],
            '128' => [
                'kategori_adi' => 'İşçi Arayanlar',
                'slug' => Str::slug('İşçi Arayanlar'),
                'ust_kategori' => 128,
                'sira' => 1,
            ],
            '129' => [
                'kategori_adi' => 'İş Arayanlar',
                'slug' => Str::slug('İş Arayanlar'),
                'ust_kategori' => 128,
                'sira' => 2,
            ],
            '130' => [
                'kategori_adi' => 'Hayvancılık',
                'slug' => Str::slug('Hayvancılık'),
                'ust_kategori' => 1,
                'sira' => 10,
            ],
            '131' => [
                'kategori_adi' => 'Arıcılık Ekipmanları',
                'slug' => Str::slug('Arıcılık Ekipmanları'),
                'ust_kategori' => 131,
                'sira' => 1,
            ],
            '132' => [
                'kategori_adi' => 'Hayvan Kaşıma Fırçası',
                'slug' => Str::slug('Hayvan Kaşıma Fırçası'),
                'ust_kategori' => 131,
                'sira' => 2,
            ],
            '133' => [
                'kategori_adi' => 'Hayvan Kesimhane Ekipmanları',
                'slug' => Str::slug('Hayvan Kesimhane Ekipmanları'),
                'ust_kategori' => 131,
                'sira' => 3,
            ],
            '134' => [
                'kategori_adi' => 'Süt Sağma Makinesi',
                'slug' => Str::slug('Süt Sağma Makinesi'),
                'ust_kategori' => 131,
                'sira' => 4,
            ],
            '135' => [
                'kategori_adi' => 'Yem Ezme & Kırma',
                'slug' => Str::slug('Yem Ezme & Kırma'),
                'ust_kategori' => 131,
                'sira' => 5,
            ],
            '136' => [
                'kategori_adi' => 'Yem Karma Makinesi',
                'slug' => Str::slug('Yem Karma Makinesi'),
                'ust_kategori' => 131,
                'sira' => 6,
            ],
            '137' => [
                'kategori_adi' => 'Yem Üretim Makinesi',
                'slug' => Str::slug('Yem Üretim Makinesi'),
                'ust_kategori' => 131,
                'sira' => 7,
            ],
            '138' => [
                'kategori_adi' => 'Ahır Ekipmanları',
                'slug' => Str::slug('Ahır Ekipmanları'),
                'ust_kategori' => 131,
                'sira' => 8,
            ],
            '139' => [
                'kategori_adi' => 'Pazar Alışveriş',
                'slug' => Str::slug('Pazar Alışveriş'),
                'ust_kategori' => null,
                'sira' => 7,
            ],
            '140' => [
                'kategori_adi' => 'Şarküteri',
                'slug' => Str::slug('Şarküteri'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '141' => [
                'kategori_adi' => 'Zeytinyağı',
                'slug' => Str::slug('Zeytinyağı'),
                'ust_kategori' => 141,
                'sira' => 1,
            ],
            '142' => [
                'kategori_adi' => 'Bal',
                'slug' => Str::slug('Bal'),
                'ust_kategori' => 141,
                'sira' => 2,
            ],
            '143' => [
                'kategori_adi' => 'Arı Sütü & Polen',
                'slug' => Str::slug('Arı Sütü & Polen'),
                'ust_kategori' => 141,
                'sira' => 3,
            ],
            '144' => [
                'kategori_adi' => 'Pekmez',
                'slug' => Str::slug('Pekmez'),
                'ust_kategori' => 141,
                'sira' => 4,
            ],
            '145' => [
                'kategori_adi' => 'Süt Ürünleri & Yumurta',
                'slug' => Str::slug('Süt Ürünleri & Yumurta'),
                'ust_kategori' => 141,
                'sira' => 5,
            ],
            '146' => [
                'kategori_adi' => 'Ayçiçek Yağı',
                'slug' => Str::slug('Ayçiçek Yağı'),
                'ust_kategori' => 141,
                'sira' => 6,
            ],
            '147' => [
                'kategori_adi' => 'Et Ürünleri',
                'slug' => Str::slug('Et Ürünleri'),
                'ust_kategori' => 141,
                'sira' => 7,
            ],
            '148' => [
                'kategori_adi' => 'Hayvansal Yağ',
                'slug' => Str::slug('Hayvansal Yağ'),
                'ust_kategori' => 141,
                'sira' => 8,
            ],
            '149' => [
                'kategori_adi' => 'Helva',
                'slug' => Str::slug('Helva'),
                'ust_kategori' => 141,
                'sira' => 9,
            ],
            '150' => [
                'kategori_adi' => 'Krem Çikolata & Ezme',
                'slug' => Str::slug('Krem Çikolata & Ezme'),
                'ust_kategori' => 141,
                'sira' => 10,
            ],
            '151' => [
                'kategori_adi' => 'Meze',
                'slug' => Str::slug('Meze'),
                'ust_kategori' => 141,
                'sira' => 11,
            ],
            '152' => [
                'kategori_adi' => 'Mısır Özü Yağı',
                'slug' => Str::slug('Mısır Özü Yağı'),
                'ust_kategori' => 141,
                'sira' => 12,
            ],
            '153' => [
                'kategori_adi' => 'Peynir',
                'slug' => Str::slug('Peynir'),
                'ust_kategori' => 141,
                'sira' => 13,
            ],
            '154' => [
                'kategori_adi' => 'Reçel & Marmelat',
                'slug' => Str::slug('Reçel & Marmelat'),
                'ust_kategori' => 141,
                'sira' => 14,
            ],
            '155' => [
                'kategori_adi' => 'Sos & Harç',
                'slug' => Str::slug('Sos & Harç'),
                'ust_kategori' => 141,
                'sira' => 15,
            ],
            '156' => [
                'kategori_adi' => 'Tahin',
                'slug' => Str::slug('Tahin'),
                'ust_kategori' => 141,
                'sira' => 16,
            ],
            '157' => [
                'kategori_adi' => 'Tereyağı',
                'slug' => Str::slug('Tereyağı'),
                'ust_kategori' => 141,
                'sira' => 17,
            ],
            '158' => [
                'kategori_adi' => 'Yağ',
                'slug' => Str::slug('Yağ'),
                'ust_kategori' => 141,
                'sira' => 18,
            ],
            '159' => [
                'kategori_adi' => 'Zeytin',
                'slug' => Str::slug('Zeytin'),
                'ust_kategori' => 141,
                'sira' => 19,
            ],
            '160' => [
                'kategori_adi' => 'Meyve & Sebze',
                'slug' => Str::slug('Meyve & Sebze'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '161' => [
                'kategori_adi' => 'Kuruyemiş',
                'slug' => Str::slug('Kuruyemiş'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '162' => [
                'kategori_adi' => 'Bakliyat',
                'slug' => Str::slug('Bakliyat'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '163' => [
                'kategori_adi' => 'Baharat',
                'slug' => Str::slug('Baharat'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '164' => [
                'kategori_adi' => 'Gıda Paketi',
                'slug' => Str::slug('Gıda Paketi'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '165' => [
                'kategori_adi' => 'Et & Balık',
                'slug' => Str::slug('Et & Balık'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '166' => [
                'kategori_adi' => 'Balık & Deniz Ürünleri',
                'slug' => Str::slug('Balık & Deniz Ürünleri'),
                'ust_kategori' => 166,
                'sira' => 1,
            ],
            '167' => [
                'kategori_adi' => 'Beyaz Et',
                'slug' => Str::slug('Beyaz Et'),
                'ust_kategori' => 166,
                'sira' => 2,
            ],
            '168' => [
                'kategori_adi' => 'Kırmızı Et',
                'slug' => Str::slug('Kırmızı Et'),
                'ust_kategori' => 166,
                'sira' => 3,
            ],
            '169' => [
                'kategori_adi' => 'Sakatat',
                'slug' => Str::slug('Sakatat'),
                'ust_kategori' => 166,
                'sira' => 4,
            ],
            '170' => [
                'kategori_adi' => 'Hazır Gıda',
                'slug' => Str::slug('Hazır Gıda'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '171' => [
                'kategori_adi' => 'İçecek',
                'slug' => Str::slug('İçecek'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '172' => [
                'kategori_adi' => 'Pastane & Fırın',
                'slug' => Str::slug('Pastane & Fırın'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '173' => [
                'kategori_adi' => 'Günlük Süt',
                'slug' => Str::slug('Günlük Süt'),
                'ust_kategori' => 140,
                'sira' => 1,
            ],
            '174' => [
                'kategori_adi' => 'Tümosan',
                'slug' => Str::slug('Tümosan'),
                'ust_kategori' => 2,
                'sira' => 8,
            ],
            '175' => [
                'kategori_adi' => 'Agrifarm',
                'slug' => Str::slug('Agrifarm'),
                'ust_kategori' => 2,
                'sira' => 9,
            ],
            '176' => [
                'kategori_adi' => 'Agripower',
                'slug' => Str::slug('Agripower'),
                'ust_kategori' => 2,
                'sira' => 10,
            ],
            '177' => [
                'kategori_adi' => 'Antonio Carraro',
                'slug' => Str::slug('Antonio Carraro'),
                'ust_kategori' => 2,
                'sira' => 11,
            ],
            '178' => [
                'kategori_adi' => 'Artrak Superline',
                'slug' => Str::slug('Artrak Superline'),
                'ust_kategori' => 2,
                'sira' => 12,
            ],
            '179' => [
                'kategori_adi' => 'Aslan Traktör',
                'slug' => Str::slug('Aslan Traktör'),
                'ust_kategori' => 2,
                'sira' => 13,
            ],
            '180' => [
                'kategori_adi' => 'Başak',
                'slug' => Str::slug('Başak'),
                'ust_kategori' => 2,
                'sira' => 14,
            ],
            '181' => [
                'kategori_adi' => 'Başkent',
                'slug' => Str::slug('Başkent'),
                'ust_kategori' => 2,
                'sira' => 15,
            ],
            '182' => [
                'kategori_adi' => 'Belarus',
                'slug' => Str::slug('Belarus'),
                'ust_kategori' => 2,
                'sira' => 16,
            ],
            '183' => [
                'kategori_adi' => 'BMC',
                'slug' => Str::slug('BMC'),
                'ust_kategori' => 2,
                'sira' => 17,
            ],
            '184' => [
                'kategori_adi' => 'Bolinder-Munktell',
                'slug' => Str::slug('Bolinder-Munktell'),
                'ust_kategori' => 2,
                'sira' => 18,
            ],
            '185' => [
                'kategori_adi' => 'Bozok',
                'slug' => Str::slug('Bozok'),
                'ust_kategori' => 2,
                'sira' => 19,
            ],
            '186' => [
                'kategori_adi' => 'Branson',
                'slug' => Str::slug('Branson'),
                'ust_kategori' => 2,
                'sira' => 20,
            ],
            '187' => [
                'kategori_adi' => 'Carraro',
                'slug' => Str::slug('Carraro'),
                'ust_kategori' => 2,
                'sira' => 21,
            ],
            '189' => [
                'kategori_adi' => 'Chery',
                'slug' => Str::slug('Chery'),
                'ust_kategori' => 2,
                'sira' => 22,
            ],
            '190' => [
                'kategori_adi' => 'Claas',
                'slug' => Str::slug('Claas'),
                'ust_kategori' => 2,
                'sira' => 23,
            ],
            '191' => [
                'kategori_adi' => 'Deutz',
                'slug' => Str::slug('Deutz'),
                'ust_kategori' => 2,
                'sira' => 24,
            ],
            '192' => [
                'kategori_adi' => 'Dexta',
                'slug' => Str::slug('Dexta'),
                'ust_kategori' => 2,
                'sira' => 25,
            ],
            '193' => [
                'kategori_adi' => 'Eicher',
                'slug' => Str::slug('Eicher'),
                'ust_kategori' => 2,
                'sira' => 26,
            ],
            '194' => [
                'kategori_adi' => 'Farmtrac',
                'slug' => Str::slug('Farmtrac'),
                'ust_kategori' => 2,
                'sira' => 27,
            ],
            '195' => [
                'kategori_adi' => 'Fendt',
                'slug' => Str::slug('Fendt'),
                'ust_kategori' => 2,
                'sira' => 28,
            ],
            '196' => [
                'kategori_adi' => 'Ferrari',
                'slug' => Str::slug('Ferrari'),
                'ust_kategori' => 2,
                'sira' => 29,
            ],
            '197' => [
                'kategori_adi' => 'Ford',
                'slug' => Str::slug('Ford'),
                'ust_kategori' => 2,
                'sira' => 30,
            ],
            '198' => [
                'kategori_adi' => 'Foton',
                'slug' => Str::slug('Foton'),
                'ust_kategori' => 2,
                'sira' => 31,
            ],
            '199' => [
                'kategori_adi' => 'Goldoni',
                'slug' => Str::slug('Goldoni'),
                'ust_kategori' => 2,
                'sira' => 32,
            ],
            '200' => [
                'kategori_adi' => 'Güldner',
                'slug' => Str::slug('Güldner'),
                'ust_kategori' => 2,
                'sira' => 33,
            ],
            '201' => [
                'kategori_adi' => 'Hanomag',
                'slug' => Str::slug('Hanomag'),
                'ust_kategori' => 2,
                'sira' => 34,
            ],
            '202' => [
                'kategori_adi' => 'Harman',
                'slug' => Str::slug('Harman'),
                'ust_kategori' => 2,
                'sira' => 35,
            ],
            '203' => [
                'kategori_adi' => 'Hars',
                'slug' => Str::slug('Hars'),
                'ust_kategori' => 2,
                'sira' => 36,
            ],
            '204' => [
                'kategori_adi' => 'Hema',
                'slug' => Str::slug('Hema'),
                'ust_kategori' => 2,
                'sira' => 37,
            ],
            '205' => [
                'kategori_adi' => 'Holder',
                'slug' => Str::slug('Holder'),
                'ust_kategori' => 2,
                'sira' => 38,
            ],
            '206' => [
                'kategori_adi' => 'Huerlimann',
                'slug' => Str::slug('Huerlimann'),
                'ust_kategori' => 2,
                'sira' => 39,
            ],
            '207' => [
                'kategori_adi' => 'IMT',
                'slug' => Str::slug('IMT'),
                'ust_kategori' => 2,
                'sira' => 40,
            ],
            '208' => [
                'kategori_adi' => 'International',
                'slug' => Str::slug('International'),
                'ust_kategori' => 2,
                'sira' => 41,
            ],
            '209' => [
                'kategori_adi' => 'İşbora',
                'slug' => Str::slug('İşbora'),
                'ust_kategori' => 2,
                'sira' => 42,
            ],
            '210' => [
                'kategori_adi' => 'JCB',
                'slug' => Str::slug('JCB'),
                'ust_kategori' => 2,
                'sira' => 43,
            ],
            '211' => [
                'kategori_adi' => 'Kaan',
                'slug' => Str::slug('Kaan'),
                'ust_kategori' => 2,
                'sira' => 44,
            ],
            '212' => [
                'kategori_adi' => 'Karataş',
                'slug' => Str::slug('Karataş'),
                'ust_kategori' => 2,
                'sira' => 45,
            ],
            '213' => [
                'kategori_adi' => 'Kioti',
                'slug' => Str::slug('Kioti'),
                'ust_kategori' => 2,
                'sira' => 46,
            ],
            '214' => [
                'kategori_adi' => 'Kubota',
                'slug' => Str::slug('Kubota'),
                'ust_kategori' => 2,
                'sira' => 47,
            ],
            '215' => [
                'kategori_adi' => 'Lamborghini',
                'slug' => Str::slug('Lamborghini'),
                'ust_kategori' => 2,
                'sira' => 48,
            ],
            '217' => [
                'kategori_adi' => 'Landini',
                'slug' => Str::slug('Landini'),
                'ust_kategori' => 2,
                'sira' => 49,
            ],
            '218' => [
                'kategori_adi' => 'Leyland',
                'slug' => Str::slug('Leyland'),
                'ust_kategori' => 2,
                'sira' => 50,
            ],
            '219' => [
                'kategori_adi' => 'LG',
                'slug' => Str::slug('LG'),
                'ust_kategori' => 2,
                'sira' => 51,
            ],
            '220' => [
                'kategori_adi' => 'Lombardin',
                'slug' => Str::slug('Lombardin'),
                'ust_kategori' => 2,
                'sira' => 52,
            ],
            '221' => [
                'kategori_adi' => 'LS Tractor',
                'slug' => Str::slug('LS Tractor'),
                'ust_kategori' => 2,
                'sira' => 53,
            ],
            '222' => [
                'kategori_adi' => 'Mahindra',
                'slug' => Str::slug('Mahindra'),
                'ust_kategori' => 2,
                'sira' => 54,
            ],
            '223' => [
                'kategori_adi' => 'Massey Harris',
                'slug' => Str::slug('Massey Harris'),
                'ust_kategori' => 2,
                'sira' => 55,
            ],
            '224' => [
                'kategori_adi' => 'McCormick',
                'slug' => Str::slug('McCormick'),
                'ust_kategori' => 2,
                'sira' => 56,
            ],
            '225' => [
                'kategori_adi' => 'Mercedes',
                'slug' => Str::slug('Mercedes'),
                'ust_kategori' => 2,
                'sira' => 57,
            ],
            '226' => [
                'kategori_adi' => 'Same',
                'slug' => Str::slug('Same'),
                'ust_kategori' => 2,
                'sira' => 58,
            ],
            '228' => [
                'kategori_adi' => 'Solis',
                'slug' => Str::slug('Solis'),
                'ust_kategori' => 2,
                'sira' => 59,
            ],
            '229' => [
                'kategori_adi' => 'Steyr',
                'slug' => Str::slug('Steyr'),
                'ust_kategori' => 2,
                'sira' => 60,
            ],
            '230' => [
                'kategori_adi' => 'Super Major',
                'slug' => Str::slug('Super Major'),
                'ust_kategori' => 2,
                'sira' => 61,
            ],
            '231' => [
                'kategori_adi' => 'Super Star',
                'slug' => Str::slug('Super Star'),
                'ust_kategori' => 2,
                'sira' => 62,
            ],
            '232' => [
                'kategori_adi' => 'Tafe',
                'slug' => Str::slug('Tafe'),
                'ust_kategori' => 2,
                'sira' => 63,
            ],
            '233' => [
                'kategori_adi' => 'Taral',
                'slug' => Str::slug('Taral'),
                'ust_kategori' => 2,
                'sira' => 64,
            ],
            '234' => [
                'kategori_adi' => 'Türk Traktör',
                'slug' => Str::slug('Türk Traktör'),
                'ust_kategori' => 2,
                'sira' => 65,
            ],
            '235' => [
                'kategori_adi' => 'TYM',
                'slug' => Str::slug('TYM'),
                'ust_kategori' => 2,
                'sira' => 66,
            ],
            '236' => [
                'kategori_adi' => 'Universal',
                'slug' => Str::slug('Universal'),
                'ust_kategori' => 2,
                'sira' => 67,
            ],
            '237' => [
                'kategori_adi' => 'Ursus',
                'slug' => Str::slug('Ursus'),
                'ust_kategori' => 2,
                'sira' => 68,
            ],
            '238' => [
                'kategori_adi' => 'Uzel Traktör',
                'slug' => Str::slug('Uzel Traktör'),
                'ust_kategori' => 2,
                'sira' => 69,
            ],
            '239' => [
                'kategori_adi' => 'Valpadana',
                'slug' => Str::slug('Valpadana'),
                'ust_kategori' => 2,
                'sira' => 70,
            ],
            '240' => [
                'kategori_adi' => 'Valtra',
                'slug' => Str::slug('Valtra'),
                'ust_kategori' => 2,
                'sira' => 71,
            ],
            '241' => [
                'kategori_adi' => 'Volvo',
                'slug' => Str::slug('Volvo'),
                'ust_kategori' => 2,
                'sira' => 72,
            ],
            '242' => [
                'kategori_adi' => 'Yağmur',
                'slug' => Str::slug('Yağmur'),
                'ust_kategori' => 2,
                'sira' => 73,
            ],
            '243' => [
                'kategori_adi' => 'YTO',
                'slug' => Str::slug('YTO'),
                'ust_kategori' => 2,
                'sira' => 74,
            ],
            '244' => [
                'kategori_adi' => 'Zetor',
                'slug' => Str::slug('Zetor'),
                'ust_kategori' => 2,
                'sira' => 75,
            ],
            '245' => [
                'kategori_adi' => 'Hayvan Pazar',
                'slug' => Str::slug('Hayvan Pazar'),
                'ust_kategori' => null,
                'sira' => 8,
            ],
            '246' => [
                'kategori_adi' => 'Kümes Hayvanları',
                'slug' => Str::slug('Kümes Hayvanları'),
                'ust_kategori' => 243,
                'sira' => 1,
            ],
            '247' => [
                'kategori_adi' => 'Büyükbaş Hayvanlar',
                'slug' => Str::slug('Büyükbaş Hayvanlar'),
                'ust_kategori' => 243,
                'sira' => 2,
            ],
            '248' => [
                'kategori_adi' => 'Yem ve Mama',
                'slug' => Str::slug('Yem ve Mama'),
                'ust_kategori' => 243,
                'sira' => 3,
            ],
            '249' => [
                'kategori_adi' => 'Aksesuarlar',
                'slug' => Str::slug('Aksesuarlar'),
                'ust_kategori' => 243,
                'sira' => 4,
            ],
            '250' => [
                'kategori_adi' => 'Küçükbaş Hayvanlar',
                'slug' => Str::slug('Küçükbaş Hayvanlar'),
                'ust_kategori' => 243,
                'sira' => 5,
            ],
            '251' => [
                'kategori_adi' => 'Akvaryum Balıkları',
                'slug' => Str::slug('Akvaryum Balıkları'),
                'ust_kategori' => 243,
                'sira' => 6,
            ],
            '252' => [
                'kategori_adi' => 'Bakım Ürünleri',
                'slug' => Str::slug('Bakım Ürünleri'),
                'ust_kategori' => 243,
                'sira' => 7,
            ],
            '253' => [
                'kategori_adi' => 'Böcekler',
                'slug' => Str::slug('Böcekler'),
                'ust_kategori' => 243,
                'sira' => 8,
            ],
            '254' => [
                'kategori_adi' => 'Deniz Canlıları',
                'slug' => Str::slug('Deniz Canlıları'),
                'ust_kategori' => 243,
                'sira' => 9,
            ],
            '255' => [
                'kategori_adi' => 'Evcil Hayvanlar',
                'slug' => Str::slug('Evcil Hayvanlar'),
                'ust_kategori' => 243,
                'sira' => 10,
            ],
            '256' => [
                'kategori_adi' => 'Sürüngenler',
                'slug' => Str::slug('Sürüngenler'),
                'ust_kategori' => 243,
                'sira' => 11,
            ],
            '257' => [
                'kategori_adi' => 'Tavuk',
                'slug' => Str::slug('Tavuk'),
                'ust_kategori' => 244,
                'sira' => 1,
            ],
            '258' => [
                'kategori_adi' => 'Hindi',
                'slug' => Str::slug('Hindi'),
                'ust_kategori' => 244,
                'sira' => 2,
            ],
            '259' => [
                'kategori_adi' => 'Kaz',
                'slug' => Str::slug('Kaz'),
                'ust_kategori' => 244,
                'sira' => 3,
            ],
            '260' => [
                'kategori_adi' => 'Horoz',
                'slug' => Str::slug('Horoz'),
                'ust_kategori' => 244,
                'sira' => 4,
            ],
            '261' => [
                'kategori_adi' => 'Ördek',
                'slug' => Str::slug('Ördek'),
                'ust_kategori' => 244,
                'sira' => 5,
            ],
            '262' => [
                'kategori_adi' => 'Devekuşu',
                'slug' => Str::slug('Devekuşu'),
                'ust_kategori' => 244,
                'sira' => 6,
            ],
            '263' => [
                'kategori_adi' => 'Güvercin',
                'slug' => Str::slug('Güvercin'),
                'ust_kategori' => 244,
                'sira' => 7,
            ],
            '264' => [
                'kategori_adi' => 'Kuğu',
                'slug' => Str::slug('Kuğu'),
                'ust_kategori' => 244,
                'sira' => 8,
            ],
            '265' => [
                'kategori_adi' => 'Kuluçkalık Yumurta',
                'slug' => Str::slug('Kuluçkalık Yumurta'),
                'ust_kategori' => 244,
                'sira' => 9,
            ],
            '266' => [
                'kategori_adi' => 'Tavus Kuşu',
                'slug' => Str::slug('Tavus Kuşu'),
                'ust_kategori' => 244,
                'sira' => 10,
            ],
            '267' => [
                'kategori_adi' => 'Boğa',
                'slug' => Str::slug('Boğa'),
                'ust_kategori' => 245,
                'sira' => 1,
            ],
            '268' => [
                'kategori_adi' => 'İnek',
                'slug' => Str::slug('İnek'),
                'ust_kategori' => 245,
                'sira' => 2,
            ],
            '269' => [
                'kategori_adi' => 'At',
                'slug' => Str::slug('At'),
                'ust_kategori' => 245,
                'sira' => 3,
            ],
            '270' => [
                'kategori_adi' => 'Deve',
                'slug' => Str::slug('Deve'),
                'ust_kategori' => 245,
                'sira' => 4,
            ],
            '271' => [
                'kategori_adi' => 'Eşek',
                'slug' => Str::slug('Eşek'),
                'ust_kategori' => 245,
                'sira' => 5,
            ],
            '272' => [
                'kategori_adi' => 'Lama',
                'slug' => Str::slug('Lama'),
                'ust_kategori' => 245,
                'sira' => 6,
            ],
            '273' => [
                'kategori_adi' => 'Manda',
                'slug' => Str::slug('Manda'),
                'ust_kategori' => 245,
                'sira' => 7,
            ],
            '274' => [
                'kategori_adi' => 'Küçükbaş & Büyükbaş',
                'slug' => Str::slug('Küçükbaş & Büyükbaş'),
                'ust_kategori' => 246,
                'sira' => 1,
            ],
            '275' => [
                'kategori_adi' => 'Balık',
                'slug' => Str::slug('Balık'),
                'ust_kategori' => 246,
                'sira' => 2,
            ],
            '276' => [
                'kategori_adi' => 'Kedi',
                'slug' => Str::slug('Kedi'),
                'ust_kategori' => 246,
                'sira' => 3,
            ],
            '277' => [
                'kategori_adi' => 'Kemirgen',
                'slug' => Str::slug('Kemirgen'),
                'ust_kategori' => 246,
                'sira' => 4,
            ],
            '278' => [
                'kategori_adi' => 'Köpek',
                'slug' => Str::slug('Köpek'),
                'ust_kategori' => 246,
                'sira' => 5,
            ],
            '279' => [
                'kategori_adi' => 'Kuş',
                'slug' => Str::slug('Kuş'),
                'ust_kategori' => 246,
                'sira' => 6,
            ],
            '280' => [
                'kategori_adi' => 'Kümes Hayvanları',
                'slug' => Str::slug('Kümes Hayvanları'),
                'ust_kategori' => 246,
                'sira' => 7,
            ],
            '281' => [
                'kategori_adi' => 'Sürüngen',
                'slug' => Str::slug('Sürüngen'),
                'ust_kategori' => 246,
                'sira' => 8,
            ],
            '282' => [
                'kategori_adi' => 'Büyükbaş & Küçükbaş',
                'slug' => Str::slug('Büyükbaş & Küçükbaş'),
                'ust_kategori' => 247,
                'sira' => 1,
            ],
            '283' => [
                'kategori_adi' => 'Kümes Hayvanları',
                'slug' => Str::slug('Kümes Hayvanları'),
                'ust_kategori' => 247,
                'sira' => 2,
            ],
            '284' => [
                'kategori_adi' => 'Balık',
                'slug' => Str::slug('Balık'),
                'ust_kategori' => 247,
                'sira' => 3,
            ],
            '285' => [
                'kategori_adi' => 'Böcekler',
                'slug' => Str::slug('Böcekler'),
                'ust_kategori' => 247,
                'sira' => 4,
            ],
            '286' => [
                'kategori_adi' => 'Kedi',
                'slug' => Str::slug('Kedi'),
                'ust_kategori' => 247,
                'sira' => 5,
            ],
            '287' => [
                'kategori_adi' => 'Kemirgen',
                'slug' => Str::slug('Kemirgen'),
                'ust_kategori' => 247,
                'sira' => 6,
            ],
            '288' => [
                'kategori_adi' => 'Köpek',
                'slug' => Str::slug('Köpek'),
                'ust_kategori' => 247,
                'sira' => 7,
            ],
            '289' => [
                'kategori_adi' => 'Kuş',
                'slug' => Str::slug('Kuş'),
                'ust_kategori' => 247,
                'sira' => 8,
            ],
            '290' => [
                'kategori_adi' => 'Sürüngen',
                'slug' => Str::slug('Sürüngen'),
                'ust_kategori' => 247,
                'sira' => 9,
            ],
            '291' => [
                'kategori_adi' => 'Toplu Satış',
                'slug' => Str::slug('Toplu Satış'),
                'ust_kategori' => 247,
                'sira' => 10,
            ],
            '292' => [
                'kategori_adi' => 'Koyun',
                'slug' => Str::slug('Koyun'),
                'ust_kategori' => 248,
                'sira' => 1,
            ],
            '293' => [
                'kategori_adi' => 'Keçi',
                'slug' => Str::slug('Keçi'),
                'ust_kategori' => 248,
                'sira' => 2,
            ],
            '294' => [
                'kategori_adi' => 'Koç',
                'slug' => Str::slug('Koç'),
                'ust_kategori' => 248,
                'sira' => 3,
            ],
            '295' => [
                'kategori_adi' => 'Kuzu',
                'slug' => Str::slug('Kuzu'),
                'ust_kategori' => 248,
                'sira' => 4,
            ],
            '296' => [
                'kategori_adi' => 'Cichlidler',
                'slug' => Str::slug('Cichlidler'),
                'ust_kategori' => 249,
                'sira' => 1,
            ],
            '297' => [
                'kategori_adi' => 'Afrika Tetraları',
                'slug' => Str::slug('Afrika Tetraları'),
                'ust_kategori' => 249,
                'sira' => 2,
            ],
            '298' => [
                'kategori_adi' => 'Amerikan Tetraları',
                'slug' => Str::slug('Amerikan Tetraları'),
                'ust_kategori' => 249,
                'sira' => 3,
            ],
            '299' => [
                'kategori_adi' => 'Arowanalar',
                'slug' => Str::slug('Arowanalar'),
                'ust_kategori' => 249,
                'sira' => 4,
            ],
            '300' => [
                'kategori_adi' => 'Canlı Doğuranlar',
                'slug' => Str::slug('Canlı Doğuranlar'),
                'ust_kategori' => 249,
                'sira' => 5,
            ],
            '301' => [
                'kategori_adi' => 'Japon Balıkları',
                'slug' => Str::slug('Japon Balıkları'),
                'ust_kategori' => 249,
                'sira' => 6,
            ],
            '302' => [
                'kategori_adi' => 'Labirentli Balıklar',
                'slug' => Str::slug('Labirentli Balıklar'),
                'ust_kategori' => 249,
                'sira' => 7,
            ],
            '303' => [
                'kategori_adi' => 'Omurgasızlar',
                'slug' => Str::slug('Omurgasızlar'),
                'ust_kategori' => 249,
                'sira' => 8,
            ],
            '304' => [
                'kategori_adi' => 'Sazansıgiller',
                'slug' => Str::slug('Sazansıgiller'),
                'ust_kategori' => 249,
                'sira' => 9,
            ],
            '305' => [
                'kategori_adi' => 'Toplu Satış',
                'slug' => Str::slug('Toplu Satış'),
                'ust_kategori' => 249,
                'sira' => 10,
            ],
            '306' => [
                'kategori_adi' => 'Vatoz & Kedi Balıkları',
                'slug' => Str::slug('Vatoz & Kedi Balıkları'),
                'ust_kategori' => 249,
                'sira' => 11,
            ],
            '307' => [
                'kategori_adi' => 'Yılan / Müren Balıkları',
                'slug' => Str::slug('Yılan / Müren Balıkları'),
                'ust_kategori' => 249,
                'sira' => 12,
            ],
            '309' => [
                'kategori_adi' => 'Büyükbaş & Küçükbaş',
                'slug' => Str::slug('Büyükbaş & Küçükbaş'),
                'ust_kategori' => 250,
                'sira' => 1,
            ],
            '310' => [
                'kategori_adi' => 'Balık',
                'slug' => Str::slug('Balık'),
                'ust_kategori' => 250,
                'sira' => 2,
            ],
            '311' => [
                'kategori_adi' => 'Kedi',
                'slug' => Str::slug('Kedi'),
                'ust_kategori' => 250,
                'sira' => 3,
            ],
            '312' => [
                'kategori_adi' => 'Kemirgen',
                'slug' => Str::slug('Kemirgen'),
                'ust_kategori' => 250,
                'sira' => 4,
            ],
            '313' => [
                'kategori_adi' => 'Köpek',
                'slug' => Str::slug('Köpek'),
                'ust_kategori' => 250,
                'sira' => 5,
            ],
            '314' => [
                'kategori_adi' => 'Kuş',
                'slug' => Str::slug('Kuş'),
                'ust_kategori' => 250,
                'sira' => 6,
            ],
            '315' => [
                'kategori_adi' => 'Kümes Hayvanları',
                'slug' => Str::slug('Kümes Hayvanları'),
                'ust_kategori' => 250,
                'sira' => 7,
            ],
            '316' => [
                'kategori_adi' => 'Sürüngen',
                'slug' => Str::slug('Sürüngen'),
                'ust_kategori' => 250,
                'sira' => 8,
            ],
            '317' => [
                'kategori_adi' => 'Arı',
                'slug' => Str::slug('Arı'),
                'ust_kategori' => 251,
                'sira' => 1,
            ],
            '318' => [
                'kategori_adi' => 'Diğer Türler',
                'slug' => Str::slug('Diğer Türler'),
                'ust_kategori' => 251,
                'sira' => 2,
            ],
            '319' => [
                'kategori_adi' => 'Geyik Böceği',
                'slug' => Str::slug('Geyik Böceği'),
                'ust_kategori' => 251,
                'sira' => 3,
            ],
            '320' => [
                'kategori_adi' => 'İpek Böceği',
                'slug' => Str::slug('İpek Böceği'),
                'ust_kategori' => 251,
                'sira' => 4,
            ],
            '321' => [
                'kategori_adi' => 'Karınca',
                'slug' => Str::slug('Karınca'),
                'ust_kategori' => 251,
                'sira' => 5,
            ],
            '323' => [
                'kategori_adi' => 'Anemonlar',
                'slug' => Str::slug('Anemonlar'),
                'ust_kategori' => 252,
                'sira' => 1,
            ],
            '324' => [
                'kategori_adi' => 'Deniz Balıkları',
                'slug' => Str::slug('Deniz Balıkları'),
                'ust_kategori' => 252,
                'sira' => 2,
            ],
            '325' => [
                'kategori_adi' => 'Deniz Yıldızı',
                'slug' => Str::slug('Deniz Yıldızı'),
                'ust_kategori' => 252,
                'sira' => 3,
            ],
            '326' => [
                'kategori_adi' => 'Karides',
                'slug' => Str::slug('Karides'),
                'ust_kategori' => 252,
                'sira' => 4,
            ],
            '327' => [
                'kategori_adi' => 'Mercan',
                'slug' => Str::slug('Mercan'),
                'ust_kategori' => 252,
                'sira' => 5,
            ],
            '328' => [
                'kategori_adi' => 'Salyangoz',
                'slug' => Str::slug('Salyangoz'),
                'ust_kategori' => 252,
                'sira' => 6,
            ],
            '329' => [
                'kategori_adi' => 'Semender',
                'slug' => Str::slug('Semender'),
                'ust_kategori' => 252,
                'sira' => 7,
            ],
            '330' => [
                'kategori_adi' => 'Yengeç',
                'slug' => Str::slug('Yengeç'),
                'ust_kategori' => 252,
                'sira' => 8,
            ],
            '331' => [
                'kategori_adi' => 'Guinea Pig / Kobay',
                'slug' => Str::slug('Guinea Pig / Kobay'),
                'ust_kategori' => 253,
                'sira' => 1,
            ],
            '332' => [
                'kategori_adi' => 'Hamster',
                'slug' => Str::slug('Hamster'),
                'ust_kategori' => 253,
                'sira' => 2,
            ],
            '333' => [
                'kategori_adi' => 'Kaplumbağa',
                'slug' => Str::slug('Kaplumbağa'),
                'ust_kategori' => 253,
                'sira' => 3,
            ],
            '334' => [
                'kategori_adi' => 'Kedi',
                'slug' => Str::slug('Kedi'),
                'ust_kategori' => 253,
                'sira' => 4,
            ],
            '335' => [
                'kategori_adi' => 'Köpek',
                'slug' => Str::slug('Köpek'),
                'ust_kategori' => 253,
                'sira' => 5,
            ],
            '336' => [
                'kategori_adi' => 'Kuş',
                'slug' => Str::slug('Kuş'),
                'ust_kategori' => 253,
                'sira' => 6,
            ],
            '337' => [
                'kategori_adi' => 'Tavşan',
                'slug' => Str::slug('Tavşan'),
                'ust_kategori' => 253,
                'sira' => 7,
            ],
            '338' => [
                'kategori_adi' => 'Bearded Dragon',
                'slug' => Str::slug('Bearded Dragon'),
                'ust_kategori' => 254,
                'sira' => 1,
            ],
            '339' => [
                'kategori_adi' => 'Bukalemun',
                'slug' => Str::slug('Bukalemun'),
                'ust_kategori' => 254,
                'sira' => 2,
            ],
            '340' => [
                'kategori_adi' => 'Diğer Cinsler',
                'slug' => Str::slug('Diğer Cinsler'),
                'ust_kategori' => 254,
                'sira' => 3,
            ],
            '341' => [
                'kategori_adi' => 'Gecko',
                'slug' => Str::slug('Gecko'),
                'ust_kategori' => 254,
                'sira' => 4,
            ],
            '342' => [
                'kategori_adi' => 'Iguana',
                'slug' => Str::slug('Iguana'),
                'ust_kategori' => 254,
                'sira' => 5,
            ],
            '343' => [
                'kategori_adi' => 'Kurbağa',
                'slug' => Str::slug('Kurbağa'),
                'ust_kategori' => 254,
                'sira' => 6,
            ],
            '344' => [
                'kategori_adi' => 'Semender',
                'slug' => Str::slug('Semender'),
                'ust_kategori' => 254,
                'sira' => 7,
            ],
            '345' => [
                'kategori_adi' => 'Solucan',
                'slug' => Str::slug('Solucan'),
                'ust_kategori' => 254,
                'sira' => 8,
            ],























        ]);
    }
}
